### ISSUE TITLE
Mermaid support

### ISSUE THREAD

**Issue by felipegambini** [emil-eklund/markdown-visual#17]
### Description
Add suport for [mermaid](https://mermaid.js.org/) markdown in Power BI

### Exemples

```mermaid
flowchart LR
   A--->B
   A--->C
   B--->D
   C--->D
```
Code:
<pre>```mermaid
flowchart LR
   A--->B
   A--->C
   B--->D
   C--->D
```</pre>

**Comment by emil-eklund** [comment]
Thank you for the suggestion, @felipegambini.
The latest version now supports mermaid diagrams. Try it out and let me know what you think!

**Comment by felipegambini** [comment]
@emil-eklund that was incredible, how quickly you implemented the improvement, congratulations and thank you very much!

I just tested it and it works great!
